# Generated by Django 5.1.3 on 2024-11-14 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0003_alter_expense_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[(None, 'Select'), ('Food', 'Food'), ('Travel', 'Travel'), ('Entertainment', 'Entertainment'), ('Health Care', 'Health Care'), ('Miscellaneous', 'Miscellaneous')], default='Select', max_length=100),
        ),
    ]
