# Generated by Django 5.1.3 on 2024-12-06 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0004_alter_expense_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[(None, 'Select'), ('Food', 'Food'), ('Travel', 'Travel'), ('Entertainment', 'Entertainment'), ('Health Care', 'Health Care'), ('Housing', 'Housing'), ('Transportation', 'Transportation'), ('Education', 'Education'), ('Personal Care', 'Personal Care'), ('Debt Payments', 'Debt Payments'), ('Savings & Investments', 'Savings & Investments'), ('Gifts & Donations', 'Gifts & Donations'), ('Insurance', 'Insurance'), ('Miscellaneous', 'Miscellaneous')], default='Select', max_length=100),
        ),
    ]
