# Generated by Django 5.1.3 on 2025-05-24 09:11

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0007_alter_user_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('year', models.IntegerField(validators=[django.core.validators.MinValueValidator(2020)])),
                ('target_amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('category', models.CharField(blank=True, choices=[(None, 'Select'), ('Food', 'Food'), ('Travel', 'Travel'), ('Entertainment', 'Entertainment'), ('Health Care', 'Health Care'), ('Housing', 'Housing'), ('Transportation', 'Transportation'), ('Education', 'Education'), ('Personal Care', 'Personal Care'), ('Debt Payments', 'Debt Payments'), ('Savings & Investments', 'Savings & Investments'), ('Gifts & Donations', 'Gifts & Donations'), ('Insurance', 'Insurance'), ('Miscellaneous', 'Miscellaneous')], max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'month', 'year', 'category')},
            },
        ),
        migrations.CreateModel(
            name='WeeklyTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start_date', models.DateField()),
                ('target_amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('category', models.CharField(blank=True, choices=[(None, 'Select'), ('Food', 'Food'), ('Travel', 'Travel'), ('Entertainment', 'Entertainment'), ('Health Care', 'Health Care'), ('Housing', 'Housing'), ('Transportation', 'Transportation'), ('Education', 'Education'), ('Personal Care', 'Personal Care'), ('Debt Payments', 'Debt Payments'), ('Savings & Investments', 'Savings & Investments'), ('Gifts & Donations', 'Gifts & Donations'), ('Insurance', 'Insurance'), ('Miscellaneous', 'Miscellaneous')], max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'week_start_date', 'category')},
            },
        ),
        migrations.CreateModel(
            name='YearlyTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(validators=[django.core.validators.MinValueValidator(2020)])),
                ('target_amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('category', models.CharField(blank=True, choices=[(None, 'Select'), ('Food', 'Food'), ('Travel', 'Travel'), ('Entertainment', 'Entertainment'), ('Health Care', 'Health Care'), ('Housing', 'Housing'), ('Transportation', 'Transportation'), ('Education', 'Education'), ('Personal Care', 'Personal Care'), ('Debt Payments', 'Debt Payments'), ('Savings & Investments', 'Savings & Investments'), ('Gifts & Donations', 'Gifts & Donations'), ('Insurance', 'Insurance'), ('Miscellaneous', 'Miscellaneous')], max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'year', 'category')},
            },
        ),
    ]
